version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amirauss-app:v14
    container_name: amirauss-app
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=http://localhost:8083
      - APP_KEY=base64:yIBwSONLRAIKAu2GFpD5zXZe+hwsJF5ROtjugD65c+4=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=amira_uss
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
    depends_on:
      - db
    command: ["/bin/bash", "/var/www/html/start-container.sh"]
    networks:
      - amira-network

  db:
    image: mariadb:10.11
    container_name: amirauss-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: amira_uss
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - amira-network

volumes:
  dbdata:

networks:
  amira-network:
    driver: bridge
